services:
  gateway:
    build: ./api-gateway
    ports: ["3000:3000"]
    environment:
      - JWT_SECRET=dev_secret
      - USER_SERVICE=user
      - PRODUCT_SERVICE=product
      - CART_SERVICE=cart
      - ORDER_SERVICE=order
      - PAYMENT_SERVICE=payment
      - PORT=3000
    depends_on: ["user", "product", "cart", "order", "payment"]

  user:
    build: ./user-service
    depends_on:
      - mysql_db
    environment:
      JWT_SECRET: dev_secret
      PORT: 3001
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: user_db

  product:
    build: ./product-service
    environment:
      - PORT=3002
      - MONGO_INITDB_HOST=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_PORT=27017
    depends_on: ["mongo"]

  cart:
    build: ./cart-service
    environment:
      - JWT_SECRET=dev_secret
      - PORT=3003

  order:
    build: ./order-service
    environment:
      - JWT_SECRET=dev_secret
      - PORT=3004

  payment:
    build: ./payment-service
    environment:
      - PORT=3005

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
